#!/usr/bin/env php
<?php
$dir = getcwd();
if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require_once $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require_once $autoload;
} else {
    fwrite(STDERR,
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

use BrainMaestro\GitHooks\Hook;
use BrainMaestro\GitHooks\Commands\AddCommand;
use BrainMaestro\GitHooks\Commands\UpdateCommand;
use BrainMaestro\GitHooks\Commands\RemoveCommand;
use BrainMaestro\GitHooks\Commands\ListCommand;
use BrainMaestro\GitHooks\Commands\HookCommand;
use Symfony\Component\Console\Application;

$application = new Application('Composer Git Hooks', '3.0.0');

// Symfony 8 prefers addCommand(), while older versions expose add().
$registerCommandMethod = method_exists($application, 'addCommand') ? 'addCommand' : 'add';

$application->{$registerCommandMethod}(new AddCommand());
$application->{$registerCommandMethod}(new UpdateCommand());
$application->{$registerCommandMethod}(new RemoveCommand());
$application->{$registerCommandMethod}(new ListCommand());

foreach (Hook::getValidHooks($dir) as $hook => $script) {
    $application->{$registerCommandMethod}(new HookCommand($hook, $script, $dir));
}

$application->run();
